<?php

/**
 * Implements hook_form_alter().
 */
function gsb_entity_reference_delete_warning_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'node_delete_confirm') {
    $nid = $form['nid']['#value'];
    gsb_entity_reference_delete_warning_test($nid);
  }
}

function gsb_entity_reference_delete_warning_test($nid) {
  //$nid = '382271';
  //$nid = '384816';
  //$nid = '312206';
  gsb_entity_reference_delete_warning_get_entity_references_to_node($nid);
}

function gsb_entity_reference_delete_warning_get_entity_references_to_node($nid) {
  $nodes = array();

  // get the field map info
  $field_map = field_info_field_map();

  // get the list of entityreference fields
  $reference_fields = array_filter($field_map, function($reference_fields) {
    return $reference_fields['type'] == 'entityreference' ? TRUE : FALSE;
  });

  // get the list of fpp fields with entityreferences
  $fpp_fields = array_filter($reference_fields, function($reference_fields) {
    return !empty($reference_fields['bundles']['fieldable_panels_pane']) ? TRUE : FALSE;
  });

  // get the list of field_collection fields with entityreferences
  $fc_fields = array_filter($reference_fields, function($reference_fields) {
    return !empty($reference_fields['bundles']['field_collection_item']) ? TRUE : FALSE;
  });

  // get the list of node fields with entityreferences
  $node_fields = array_filter($reference_fields, function($reference_fields) {
    return !empty($reference_fields['bundles']['node']) ? TRUE : FALSE;
  });

  $found_nodes = array();
  foreach($node_fields as $field_name => $field_info) {
    $type = 'node';
    $nodes = array_merge(gsb_entity_reference_delete_warning_get_field_references_to_node($field_name, $type, $nid), $nodes);
  }
  $nodes = array_merge($nodes, $found_nodes);

  $found_nodes = array();
  foreach($fc_fields as $field_name => $field_info) {
    $type = 'fc';
    $nodes = array_merge(gsb_entity_reference_delete_warning_get_field_references_to_node($field_name, $type, $nid), $nodes);
  }
  $nodes = array_merge($nodes, $found_nodes);

  $found_nodes = array();
  foreach($fpp_fields as $field_name => $field_info) {
    $type = 'fpp';
    $nodes = array_merge(gsb_entity_reference_delete_warning_get_field_references_to_node($field_name, $type, $nid), $nodes);
  }
  $nodes = array_merge($nodes, $found_nodes);

  $nodes = array_unique($nodes, SORT_REGULAR);
  dpm($nodes);
}

function gsb_entity_reference_delete_warning_get_field_references_to_node($field_name, $type, $nid) {
  $nodes = array();
  if ($type == 'node') {
    $records = gsb_entity_reference_delete_warning_getTargetInfo($field_name, $nid);
    foreach ($records as $record) {
      $nodes[] = $record->entity_id;
    }
  }
  else if ($type == 'fc') {
    $records = gsb_entity_reference_delete_warning_getTargetInfo($field_name, $nid);
    foreach ($records as $record) {
      $entity_id = $record->entity_id;
      $value_field_name = $record->bundle;
      $value_records = gsb_entity_reference_delete_warning_getValueInfo($entity_id, $value_field_name);
      foreach ($value_records as $value_record) {
        $nodes[] = $value_record->entity_id;
      }
    }
  }
  else if ($type == 'fpp') {
    $records = gsb_entity_reference_delete_warning_getTargetInfo($field_name, $nid);
    foreach ($records as $record) {
      $fpid = $record->entity_id;
      $fpp_records = gsb_entity_reference_delete_warning_getSubTypeInfo($fpid);
      foreach ($fpp_records as $fpp_record) {
        $uuid = $fpp_record->uuid;
        $pane_records = gsb_entity_reference_delete_warning_getPaneInfo($uuid);
        foreach ($pane_records as $pane_record) {
          $did = $pane_record->did;
          $entity_records = gsb_entity_reference_delete_warning_getPanelizerEntityInfo($did);
          foreach ($entity_records as $entity_record) {
            $nodes[] = $entity_record->entity_id;
          }
        }
      }
    }
  }
  return $nodes;
}

function gsb_entity_reference_delete_warning_getTargetInfo($field_name, $target_id) {
  $target_field_name = $field_name . '_target_id';
  $table_name = 'field_data_' . $field_name;
  $result = db_select($table_name, 'fd')
    ->fields('fd', array('bundle', 'entity_id', $target_field_name))
    ->condition('fd.'.$target_field_name, $target_id, '=')
    ->execute();
  $records = array();
  foreach ($result as $record) {
    $records[] = $record;
  }
  return $records;
}

function gsb_entity_reference_delete_warning_getValueInfo($entity_id, $field_name) {
  $value_field_name = $field_name . '_value';
  $value_table_name = 'field_data_' . $field_name;
  $result = db_select($value_table_name, 'fd')
    ->fields('fd', array('bundle', 'entity_id', $value_field_name))
    ->condition('fd.'.$value_field_name, $entity_id, '=')
    ->execute();
  $records = array();
  foreach ($result as $record) {
    $records[] = $record;
  }
  return $records;
}

function gsb_entity_reference_delete_warning_getSubTypeInfo($fpid) {
  //dpm('fpid = ' . $fpid);
  $result = db_select('fieldable_panels_panes', 'fpp')
    ->fields('fpp', array('fpid', 'bundle', 'uuid'))
    ->condition('fpp.fpid', $fpid, '=')
    ->execute();
  $records = array();
  foreach ($result as $record) {
    $records[] = $record;
  }
  return $records;
}

function gsb_entity_reference_delete_warning_getPaneInfo($uuid) {
  $subtype = 'uuid:' . $uuid;
  //dpm('subtype = ' . $subtype);
  $result = db_select('panels_pane', 'pp')
    ->fields('pp', array('pid', 'did', 'subtype'))
    ->condition('pp.subtype', $subtype, '=')
    ->execute();
  $records = array();
  foreach ($result as $record) {
    $records[] = $record;
  }
  return $records;
}

function gsb_entity_reference_delete_warning_getPanelizerEntityInfo($did) {
  //dpm('did = ' . $did);
  $result = db_select('panelizer_entity', 'pe')
    ->fields('pe', array('entity_type', 'entity_id', 'did'))
    ->condition('pe.did', $did, '=')
    ->execute();
  $records = array();
  foreach ($result as $record) {
    $records[] = $record;
  }
  return $records;
}
